### ISSUE TITLE
How to destroy an emdedded Map Object

### ISSUE THREAD

**Issue by Koreatanne** [tillnagel/unfolding#110]
I am Using the Unfolding Maps API. I have created an Subclass of PApplet which contains an UnfoldingMap (OPENGL Renderer). This PApplet-Subclass I have Embedded in a Java-Eclipse Project. To save Resources, I want the Papplet Object to be destroyed if its panel is not shown. When I try to destroy the object by doing:

```
PApplet.stop();
PApplet.destroy();
```
an Exception is raised (destroy - line):
java.lang.NullPointerException
	at jogamp.opengl.gl4.GL4bcImpl.glDeleteTextures(GL4bcImpl.java:4095)
	at processing.opengl.PJOGL.deleteTextures(PJOGL.java:1977)
	at processing.opengl.PGraphicsOpenGL.deleteFinalizedTextureObjects(PGraphicsOpenGL.java:802)
	at processing.opengl.PGraphicsOpenGL.deleteFinalizedGLResources(PGraphicsOpenGL.java:1197)
	at processing.opengl.PGraphicsOpenGL.dispose(PGraphicsOpenGL.java:648)
	at processing.core.PApplet.dispose(PApplet.java:4145)
	at processing.core.PApplet.destroy(PApplet.java:1207)
        [...]

Do You have any Idea why it can´t be destroyed?

**Comment by tillnagel** [comment]
Not sure I understand. Why do you think this is related to Unfolding, and not to Processing?

**Comment by Koreatanne** [comment]
You are right. If I don´t use an UnfoldingMap Object the error occurs, too.
I moved this Question to processing forum;
