### ISSUE TITLE
MapProvider: AcetatProvider does not work

### ISSUE THREAD

**Issue by PDXIII** [tillnagel/unfolding#126]
While testing all nested classes, the following error occurs.
The app window opens, but stays gray and the console shows the following message:

	java.net.UnknownHostException: a.acetate.geoiq.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at processing.core.PApplet.createInputRaw(PApplet.java:6735)
	at processing.core.PApplet.createInput(PApplet.java:6693)
	at processing.core.PApplet.loadBytes(PApplet.java:6912)
	at processing.core.PApplet.loadImage(PApplet.java:5292)
	at de.fhpotsdam.unfolding.tiles.TileLoader.getTileFromUrl(Unknown Source)
	at de.fhpotsdam.unfolding.tiles.TileLoader.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
	The file "http://a.acetate.geoiq.com/tiles/acetate-hillshading/10/550/335.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.

**Comment by eialbur** [comment]
I ran into a similar (but still somewhat different) scenario. If you notice in the main methods the fully qualified name of your class is passed into PApplet as follows:
	PApplet.main(new String[] { "de.fhpotsdam.unfolding.examples.data.GPXTrackApp" });

However, the packages for examples have been rearranged and passing in the wrong name can lead to all sorts of errors. When I run into this issues I modify the code as follows:
        PApplet.main(new String[] { GPXTrackApp.class.getName() });

**Comment by tillnagel** [comment]
Send us an e-mail to get the Unfolding beta for P3.
