### ISSUE TITLE
Choropleth Map App Example Broken

### ISSUE THREAD

**Issue by jimbglenn** [tillnagel/unfolding#128]
This example (\unfolding-master\examples-processing\ChoroplethMapApp)
does not work.  It complains about missing "quality" parameter.

If I remove P2D from size, the application runs but no markers are colored.

Any suggestions would be appreciated.

**Comment by cpietsch** [comment]
Looks like a general bug.
I got the same error in the bundled version of unfolding for processing, the dev version instead is working fine.
This is a incompatibility with processing 3 bug. Wait for the new unfolding release or use the github version.

`Unfolding Map v0.9.6
java.lang.RuntimeException: java.lang.NoSuchFieldError: quality
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:449)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldError: quality
	at de.fhpotsdam.unfolding.mapdisplay.OpenGLMapDisplay.<init>(Unknown Source)
	at de.fhpotsdam.unfolding.mapdisplay.MapDisplayFactory.getMapDisplay(Unknown Source)
	at de.fhpotsdam.unfolding.UnfoldingMap.<init>(Unknown Source)
	at de.fhpotsdam.unfolding.UnfoldingMap.<init>(Unknown Source)
	at ChoroplethMapApp.setup(ChoroplethMapApp.java:47)
	at processing.core.PApplet.handleDraw(PApplet.java:2377)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:859)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
`

**Comment by masterflorin** [comment]
Try using OPENGL instead of P2D.
