### ISSUE TITLE
Cannot Use Own Map Styles

### ISSUE THREAD

**Issue by dnnssgl** [tillnagel/unfolding#136]
Hi There,

I am using Unfolding Maps in Processing 2.2.1 and it's working just fine until I tried to import my own styling.

According to their [tutorial page](http://unfoldingmaps.org/tutorials/mapprovider-and-tiles.html) - which is pretty bad documented - I just need to import a mbtiles file

```
String tilesStr = sketchPath("data/control-room.mbtiles");
 map = new UnfoldingMap(this, new MBTilesMapProvider(tilesStr));
```

I generated a mbtiles file with TileMill from the _Control Room_ example and it seems to be fine but when running the following sketch..

```
import de.fhpotsdam.unfolding.*;
import de.fhpotsdam.unfolding.utils.*;

UnfoldingMap map;
import de.fhpotsdam.unfolding.providers.MBTilesMapProvider;

 
void setup() {
  size(800, 600);
 
  String tilesStr = sketchPath("data/control-room.mbtiles");
  map = new UnfoldingMap(this, new MBTilesMapProvider(tilesStr));
  MapUtils.createDefaultEventDispatcher(this, map);
  map.setZoomRange(2, 4);
}
 
void draw() {
  map.draw();
}
```

.. I get a long list of exceptions:

```
Unfolding Map v0.9.6
No OpenGL renderer. Using Java2DMapDisplay.
java.lang.ClassNotFoundException: org.sqlite.JDBC
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:190)
	at de.fhpotsdam.unfolding.tiles.MBTilesLoaderUtils.getMBTileData(Unknown Source)
	at de.fhpotsdam.unfolding.tiles.MBTilesLoaderUtils.getMBTile(Unknown Source)
	at de.fhpotsdam.unfolding.providers.MBTilesMapProvider.getTile(Unknown Source)
	at de.fhpotsdam.unfolding.tiles.TileLoader.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.ClassNotFoundException: org.sqlite.JDBC
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
...
```

Any idea on how to fix this?

**Comment by tillnagel** [comment]
Thanks for the feedback! We think our documentation is not too bad. In the linked tutorial you'll find you need to import the SQLite library - which is the reason if your exception.

**Comment by dnnssgl** [comment]
Ah thanks! To be more precise, the code examples are kind of suboptimal as they miss the important lines with the additional libraries. So you have to know which ones you'd need which makes it pretty difficult and frustrating for beginners.
