### ISSUE TITLE
403 for URL Google Terrain Provider

### ISSUE THREAD

**Issue by Forge-Media** [tillnagel/unfolding#141]
Currently getting an error 403 when trying to use the Google Terrain Provider. Do I not need to supply an API key?

```
java.io.IOException: Server returned HTTP response code: 403 for URL: http://mt1.google.com/vt/v=w2p.116&hl=de&x=449&y=272&z=10&s=Galileo
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at processing.core.PApplet.createInputRaw(PApplet.java:6793)
	at processing.core.PApplet.createInput(PApplet.java:6744)
	at processing.core.PApplet.loadBytes(PApplet.java:6962)
	at processing.core.PApplet.loadImage(PApplet.java:5330)
	at de.fhpotsdam.unfolding.tiles.TileLoader.getTileFromUrl(Unknown Source)
	at de.fhpotsdam.unfolding.tiles.TileLoader.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tillnagel** [comment]
All map providers are for educational purposes, only. For me, the URL your tried to access (from the exception message) [works fine](http://mt1.google.com/vt/v=w2p.116&hl=de&x=449&y=272&z=10&s=Galileo). Google returns a 403 when you are requesting too many tiles in a too short time frame.
